// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// schedule.js
export const SCHEDULE_MEETING_SUCCESS = 'SCHEDULE_MEETING_SUCCESS'
export const SCHEDULE_MEETING_FAILURE = 'SCHEDULE_MEETING_FAILURE'
export const GET_MY_MEETINGS_SUCCESS = 'GET_MY_MEETINGS_SUCCESS'
export const GET_MY_MEETINGS_FAILURE = 'GET_MY_MEETINGS_FAILURES'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'
